Basic setup
loconav-tech/loconav-developer-apis pull request #1
Opened 2023-09-20 12:18 UTC by gaurav4ever

**What**
- Basic setup of Rails project

2023-09-21 03:37 UTC, gagan93jtg requested changes

2023-09-21 03:37 UTC, gagan93jtg commented on Dockerfile
> +CMD ["rails", "server", "-b", "0.0.0.0"]
configure your editor to add new line at the end of file.

2023-09-21 03:37 UTC, gagan93jtg commented on app/helpers/authentication_helper.rb
> +      render json: Loconav::Response::Builder.failure(errors: ["Authentication failed"])
Let's set a HTTP status code indicating the specific failure

2023-09-21 03:37 UTC, gagan93jtg commented on app/helpers/authentication_helper.rb
> +    return false unless request.headers['User-Authentication'].present?
`return false unless auth_token.present?`

2023-09-21 03:37 UTC, gagan93jtg commented on app/helpers/authentication_helper.rb
> +    request.headers['User-Authentication']
move name to a constant

2023-09-21 03:37 UTC, gagan93jtg commented on app/services/drivers/query_service.rb
> +      search_driver
No point calling a method from a method. Let's write code inside run method. Incase we end up writing a lot of it, we'll split the same into methods

2023-09-21 03:37 UTC, gagan93jtg commented on app/services/drivers/query_service.rb
> +    attr_accessor :account, :params
Let's keep possibility of error in all services. Errors can happen if the user does not have access to query the resource (eg. drivers here), or when some query parameter is wrongly supplied. Correspondingly, the structure of controller would be something like [this](https://github.com/loconav-tech/fastag-service/blob/main/app/controllers/api/v1/transactions_controller.rb#L14)

2023-09-21 03:37 UTC, gagan93jtg commented on app/services/drivers/query_service.rb
> +      driver = Linehaul::DriverService.new(account['authentication_token']).fetch_drivers({ name: params[:name] })
Linehaul's query service shouldn't rely as code in this service. It should be a gem (SDK created through linehaul's swagger doc).

2023-09-21 03:37 UTC, gagan93jtg commented on app/services/linehaul/auth_service.rb
> +          Authorization: "NGuyXn9TsUVt_UpYjCzs"
hardcoding

2023-09-21 03:37 UTC, gagan93jtg commented on app/services/linehaul/auth_service.rb
> +    USER_DETAILS_URL = LINEHAUL_BASE_URL + "/api/v5/partner/user_details"
let's authenticate through identity. cc @nimish-mehta.
The SDK is ready I believe.

2023-09-21 03:37 UTC, gagan93jtg commented on config/cable.yml
> +development:
Let's disable action cable. We don't need it.

2023-09-21 03:37 UTC, gagan93jtg commented on config/credentials.yml.enc
> +sjFBXVE94sOz5ACaRit2aZ9/nJcPAhJpOoTXol5vN2zw27Tfla0eQN9tiLLHfEn+PxmqPXiYbbzWYQpVmnwTwQMX6SLG2hngXak2Rzx4jlit0Q0Z1Q8m9QKn8GD6a2ZWVlLCd2lWcbHLUW6J9mzQ/Xj6UeLtVNtsMt62DKuQSaXKhhHM0Ef0yQB4eaTJ9jkAGmsseOz
We don't need this too. We'll use config server to load credentials.

2023-09-21 03:37 UTC, gagan93jtg commented on config/initializers/constants.rb
> +LINEHAUL_BASE_URL = "https://linehaul.stg13.loconav.dev"
Let's integrate the dotenv gem for local and use secrets.yml to load such urls. 
Config server for non-dev envs.

2023-09-21 03:37 UTC, gagan93jtg commented on config/initializers/cors.rb
> +# Be sure to restart your server when you modify this file.
can delete such files (completely commented)

2023-09-21 03:37 UTC, gagan93jtg commented on config/routes.rb
> +    namespace :v1 do
Are we calling this v1 or v2? I believe customers are already having our v1.

2023-09-21 03:37 UTC, gagan93jtg commented on test/channels/application_cable/connection_test.rb
> +require "test_helper"
please add and configure rspec for test cases. Default (this) is minitest.

2023-09-21 03:37 UTC, gagan93jtg commented on app/helpers/response_helper.rb
> +      raise StandardError, DEFAULT_ERROR_MSG
We'd want to raise custom classes in order to catch those and handle in response. Raising StandardError means catching StandardError somewhere later (to avoid HTTP 500) and that would catch almost everything

2023-09-21 03:37 UTC, gagan93jtg commented on app/controllers/api/v1/drivers_controller.rb
> +      # GET /api/v1/drivers
let's skip comments and make sure (that we've already done here) that routes and file hierarchies are synonymous.

2023-09-21 03:38 UTC, gagan93jtg commented
@gaurav4ever let's file an EPIC if not already there. After that, create JIRA for whatever you're doing and use the same branch in git.

2023-09-21 03:38 UTC, gagan93jtg commented on README.md
> +APIs used by clients via developers.loconav.com
This might be called developers.a.loconav.com as it points to a specific loconav deployment.

2023-09-21 09:01 UTC, gaurav4ever commented on app/services/linehaul/auth_service.rb
> +    USER_DETAILS_URL = LINEHAUL_BASE_URL + "/api/v5/partner/user_details"
Sure, will integrate that

2023-09-22 02:49 UTC, ShubhamGupta commented on app/helpers/authentication_helper.rb
> +    return false unless request.headers['User-Authentication'].present?
Can refactor to `return !!auth_token`

2023-09-22 03:04 UTC, ShubhamGupta requested changes

2023-09-22 03:04 UTC, ShubhamGupta commented on config/initializers/cors.rb
> +# Be sure to restart your server when you modify this file.
Lets not delete anything which was automatically generated either by rails or by some gem. One reason to keep such files is that they remind you in future that you can tweak these to make changes to your application.

2023-09-22 05:23 UTC, gaurav4ever commented on config/routes.rb
> +    namespace :v1 do
V2

2023-09-22 11:30 UTC, gaurav4ever commented on app/controllers/api/v1/drivers_controller.rb
> +      # GET /api/v1/drivers
These are autogenerated comments.

2023-12-04 10:34 UTC, closed without merging