LCNV-33146 : Geofence CRUD
loconav-tech/loconav-developer-apis pull request #32
Opened 2024-01-02 11:33 UTC by nishantbansal1910

2024-01-08 05:31 UTC, gaurav4ever requested changes
Add new line at the end in each new file

2024-01-08 05:31 UTC, gaurav4ever commented on app/controllers/api/v1/polygons_controller.rb
> +      end
Use from utilhelper

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/polygon/query_service.rb
> +        handle_errors("Techincal_issue")
This will not match with switch case

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/linehaul/polygon_service.rb
> +      start_index = pagination[:page] * pagination[:per_page]
`.to_i` on every math functions

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/linehaul/polygon_service.rb
> +          "Authorization": auth_token,
No need to double quotes

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/linehaul/polygon_service.rb
> +end
Add a new empty line

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/polygon/creation_service.rb
> +end
Add a new empty line

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/polygon/query_service.rb
> +end
Add a new empty line

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/polygon/updation_service.rb
> +end
Add a new empty line

2024-01-08 05:31 UTC, gaurav4ever commented on app/controllers/api/v1/polygons_controller.rb
> +end
Add a new empty line

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/polygon/creation_service.rb
> +    def validate_params
Add validation on distance_unit as well. On `m` should be allowed 
https://github.com/loconav-tech/marketplace/blob/master/src/main/java/com/loconav/marketplace/partner/enums/DistanceUnit.java

2024-01-08 05:31 UTC, gaurav4ever commented on app/services/polygon/updation_service.rb
> +        handle_errors("Technical issue, please try again later")
This will not match with switch case

2024-01-15 09:37 UTC, gaurav4ever requested changes

2024-01-15 09:37 UTC, gaurav4ever commented on app/services/linehaul/polygon_service.rb
> +      start_index = ((pagination[:page]-1) * pagination[:per_page]).to_i
Code not formatted.

`start_index = ((pagination[:page].to_i - 1) * pagination[:per_page].to_i)`

2024-01-15 09:37 UTC, gaurav4ever commented on app/services/polygon/creation_service.rb
> +      create_polygon if errors.empty?
move `if errors.empty?` inside method

2024-01-15 09:37 UTC, gaurav4ever commented on app/services/polygon/creation_service.rb
> +
remove new line

2024-01-15 09:37 UTC, gaurav4ever commented on app/services/polygon/creation_service.rb
> +    QUERY_PARAMS = %i[name lat radius long distance_unit active]
This is a creation service. Don't use **QUERY_PARAMS** name. 
Use **PERMITTED_PARAMS**

2024-01-15 09:37 UTC, gaurav4ever commented on app/services/polygon/creation_service.rb
> +    REQUIRED_PARAMS = %w[name lat long radius]
We can name this **MANDATORY_PARAMS**

2024-01-15 09:37 UTC, gaurav4ever commented on app/services/polygon/updation_service.rb
> +    QUERY_PARAMS = %i[name lat radius long distance_unit active]
QUERY_PARAMS -> PERMITTED_PARAMS

2024-01-15 09:37 UTC, gaurav4ever commented on app/controllers/api/v1/polygons_controller.rb
> +      def index
permitted params ?

2024-01-15 09:37 UTC, gaurav4ever commented on config/secrets.yml
> -  redis_db_index: <%= ENV.fetch("REDIS_DB_INDEX") || '0' %>
revert

2024-01-22 11:45 UTC, nishantbansal1910 commented on app/services/polygon/creation_service.rb
> +
same as another code

2024-01-23 07:28 UTC, gaurav4ever approved these changes

2024-01-23 07:29 UTC, merged