throttler implementation and db layes and apis
loconav-tech/loconav-developer-apis pull request #7
Opened 2023-11-22 10:00 UTC by nishantbansal1910

2023-11-22 11:28 UTC, gaurav4ever requested changes
1. Code is not formatted.
2. Do `rubocop -a` to fix ruby related issues

2023-11-22 11:28 UTC, gaurav4ever commented on Gemfile
> +gem 'byebug'
move this in development and test group

2023-11-22 11:28 UTC, gaurav4ever commented on Rakefile
> +Rails.application.load_tasks
Do we need this file ? Rake is not installed

2023-11-22 11:28 UTC, gaurav4ever commented on app/controllers/api/v1/drivers_controller.rb
> +      before_action :do_filter_internal
add new line

2023-11-22 11:28 UTC, gaurav4ever commented on app/controllers/api/v1/throttler_controller.rb
> +          scope: params[:scope],)
Do this in Throttler::CreationService

2023-11-22 11:28 UTC, gaurav4ever commented on app/controllers/api/v1/throttler_controller.rb
> +        total_count = ThrottlerConfig.count
Move this and pagination logic in Throttler::QueryService. Separate the logics. 

Controller class should not do any processing on models

2023-11-22 11:28 UTC, gaurav4ever commented on app/controllers/api/v1/throttler_controller.rb
> +        client_response = ThrottlerConfig.find_by(auth_token:auth_token)
move in  Throttler::QueryService make different method for this

2023-11-22 11:28 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +  def get_config(key)
private

2023-11-22 11:28 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +  HEADER_USER_AUTHENTICATION = "User-Authentication".freeze
Don't hardcode, use from secrets instead

2023-11-22 11:28 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +  mattr_accessor :client_map
why mattr_accessor?

2023-11-22 11:28 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +    elsif client_map["api_config"][:api_config]["#{endpoint},#{http_method}"].present?
api config inside api_config?

2023-11-22 11:28 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +  def do_filter_internal
change name to `do_throttle`

2023-11-22 11:28 UTC, gaurav4ever commented on app/services/throttler/throttler_service.rb
> +  class ThrottlerService
module should be Throttler and there should be 3 service class
1. creation_service
2. updation_service
3. query_service.
each class should have its own error handling

Refactor accordingly

2023-11-22 11:28 UTC, gaurav4ever commented on app/services/throttler/throttler_service.rb
> +    def update_api_config(api_config_map, api_config)
private

2023-11-22 11:28 UTC, gaurav4ever commented on app/services/throttler/throttler_service.rb
> +      if params[:api_config].nil?
why we need this check ?

2023-11-23 07:16 UTC, nishantbansal1910 commented on app/controllers/api/v1/drivers_controller.rb
> +      before_action :do_filter_internal
needs to be done in application controller

2023-11-23 07:48 UTC, nishantbansal1910 commented on app/services/throttler/throttler_service.rb
> +      if params[:api_config].nil?
this check is for to update api_config_map to previous api config if params[:api_config] is null.

2023-11-23 07:54 UTC, nishantbansal1910 commented on app/helpers/throttler_helper.rb
> +    elsif client_map["api_config"][:api_config]["#{endpoint},#{http_method}"].present?
one is the key for client map and other one is key inside hash value for client map.
changed key name from `api_config`  to `global api config`

2023-11-23 09:24 UTC, nishantbansal1910 commented on app/helpers/throttler_helper.rb
> +  mattr_accessor :client_map
working on class level.

2023-11-24 06:48 UTC, gaurav4ever requested changes

2023-11-24 06:48 UTC, gaurav4ever commented on app/models/throttler_config.rb
> +        api_config_map["#{config['endpoint']},#{config['method']}"] = config
Since we are doing more than just validating the api_config. We need separation of concern in the code. 
instead of validate callback. Use before create callback. 
in that method, create a separate private method for validation

2023-11-24 06:48 UTC, gaurav4ever commented on app/services/throttler/updation_service.rb
Refactor this code

2023-11-24 06:48 UTC, gaurav4ever commented on bin/bundle
> +    return gemfile if gemfile.present?
revert

2023-11-24 06:48 UTC, gaurav4ever commented on config/routes.rb
> +      get "throttler/:auth_token", to: "throttler#get_by_auth_token"
```

resources :throttler, only: [:index, :create, :update] do
        collection do
          get ":auth_token", action: :get_by_auth_token, on: :member
        end
      end
```

2023-11-24 06:48 UTC, gaurav4ever commented on config/secrets.yml
> +  linehaul_base_url: https://linehaul.stg13.loconav.dev
revert

2023-11-24 06:48 UTC, gaurav4ever commented on config/secrets.yml
> +  header_user_authentication: User-Authentication
fetch from ENV.

2023-11-24 06:48 UTC, gaurav4ever commented on db/migrate/20231115072721_add_scope_to_throttler_config.rb
> +class AddScopeToThrottlerConfig < ActiveRecord::Migration[7.0]
Remove this file and make final migration file for this table

2023-11-24 07:57 UTC, nishantbansal1910 commented on config/routes.rb
> +      get "throttler/:auth_token", to: "throttler#get_by_auth_token"
on: :member ?

2023-11-28 11:29 UTC, gaurav4ever requested changes

2023-11-28 11:29 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +        client_map["global api config"] = { api_config: config.api_config }
`global_api_config`

2023-11-28 11:29 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +    }
```
client = client_map[key] || client_map["global api config"]
  api_config = client&.dig(:api_config, "#{endpoint},#{http_method}")

  limit = api_config&.fetch("limit", client&.fetch(:limit, DEFAULT_THROTTLING_LIMIT))
  window = api_config&.fetch("window", client&.fetch(:window, DEFAULT_THROTTLING_WINDOW))
  redis_key = api_config ? "#{key}#{endpoint}" : key

  { limit: limit, window: window, redis_key: redis_key }
```

2023-11-28 11:29 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +  def self.client_reload_cron
as there is no cron yet. Just name it `reload_clients`

2023-11-28 11:29 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +    response.headers["X-Rate-Limit-Limit"] = throttle_config[:limit].to_s
Do this in a new private method `set_throttle_headers`

2023-11-28 11:29 UTC, gaurav4ever commented on app/helpers/throttler_helper.rb
> +    }
```
client = client_map[key] || client_map["global api config"]
    api_config = client&.dig(:api_config, "#{endpoint},#{http_method}")

    limit = api_config&.fetch("limit", client&.fetch(:limit, DEFAULT_THROTTLING_LIMIT))
    window = api_config&.fetch("window", client&.fetch(:window, DEFAULT_THROTTLING_WINDOW))
    redis_key = api_config ? "#{key}#{endpoint}" : key

    { limit: limit, window: window, redis_key: redis_key }
```

2023-12-05 10:25 UTC, nishantbansal1910 commented on config/initializers/throttler.rb
> +REDIS = Redis.new(host: Rails.application.secrets.redis_host, port: 6379)
taking from secrets.

2023-12-05 12:17 UTC, nishantbansal1910 commented on config/routes.rb
> +      end
can't be changed

2024-01-02 09:13 UTC, closed without merging